version: 2.1
jobs:
  yarninstall:
    docker:
      - image: cimg/node:lts
        auth:
          username: henriboulnois
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
          - npm-v2-dependencies-{{ checksum "yarn.lock" }}
          - npm-v2-dependencies
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-v2-dependencies-{{ checksum "yarn.lock" }}
  yarnlint:
    docker:
      - image: cimg/node:lts
        auth:
          username: henriboulnois
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
          - npm-v2-dependencies-{{ checksum "yarn.lock" }}
          - npm-v2-dependencies
      - run: yarn lint
      - run: yarn format:check
      - save_cache:
          paths:
            - node_modules
          key: npm-v2-dependencies-{{ checksum "yarn.lock" }}
  unittest:
    docker:
      - image: cimg/node:lts
        auth:
          username: henriboulnois
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: yarn test

workflows:
  build:
    jobs:
      - yarninstall
      - yarnlint:
          requires:
          - yarninstall
      - unittest:
          requires:
          - yarninstall
          - yarnlint