version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - restore_cache:
          keys:
          - npm-v1-dependencies-{{ checksum "yarn.lock" }}
          - npm-v1-dependencies
      - run: yarn install
      - save_cache:
          paths:
            - "node_module"
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}