version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - restore_cache:
          keys:
          - npm-v1-dependencies-{{ checksum "yarn.lock" }}
      - checkout
      - run:
          name: "Testing"
          command: yarn install